import globals from './globals.css';
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer"; // Ensure Footer is properly imported

export const metadata = {
  title: "Create Next App", // You can customize the title here
  description: "Generated by create next app", // Customize the description as needed
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
          {children}
          <Footer /> {/* Footer component */}
        </div>
      </body>
    </html>
  );
}
